spring:
  data:
    mongodb:
      uri: mongodb://admin:vawaadmin@voicebox-shard-00-00-phrma.mongodb.net:27017,voicebox-shard-00-01-phrma.mongodb.net:27017,voicebox-shard-00-02-phrma.mongodb.net:27017/test?ssl=true&replicaSet=VoiceBox-shard-0&authSource=admin&retryWrites=true&w=majority
